### ISSUE TITLE
Failed to run task "lint"

### ISSUE THREAD

**Issue by rao014** [open-lasso-python/lasso-python#23]
**🐛 Describe the bug**

**🔢 To Reproduce**

run > task lint 
Observed on VS Code (Windows)

**💘 Expected behavior**
Linting check works

**📷 Screenshots**
![image](https://user-images.githubusercontent.com/11404575/197339511-a2f5a19e-7b38-4452-9e27-19e5a783f0b7.png)

**🖥️ Setup**
 - lasso-python version: [e.g. 1.5.1]
 - OS: Windows

**ℹ️ Additional context**
possible solution: remove python3 -m from the lint task in poetry file

**Comment by codie3611** [comment]
@rao014 how should we proceed here? Do I understand to simply remove `python3 -m` and just do `poetry ...`?

**Comment by rao014** [comment]
@codie3611 It works now on my PC. 
No idea why! Closing this issue.
