### ISSUE TITLE
Checking ispgfh1 == 11 

### ISSUE THREAD

**Issue by osullivryan** [open-lasso-python/lasso-python#34]
https://github.com/open-lasso-python/lasso-python/blob/2efed713789285ab5840fe6c5c50f0a72c8eeb3b/lasso/dyna/d3plot.py#L2232

I think the ispgfh1 entry in the sph header is actually the number of SPH particles (or around that), and therefor this check throws an error when it shouldn't. 

I don't quite know how to interpret the LS-DYNA binary manual for this portion of the d3plot file, however!

![image](https://user-images.githubusercontent.com/17506844/212437213-ed432eca-6bad-4e5a-948d-36ac75736876.png)

**Comment by codie3611** [comment]
Hmmmm I agree there might be a false alarm. What solver version do you use and what is the exact error?

**Comment by osullivryan** [comment]
Close for now as I need to do some more investigation!
