### ISSUE TITLE
Nodout missing on windows

### ISSUE THREAD

**Issue by codie3611** [open-lasso-python/lasso-python#35]
**🐛 Describe the bug**

### From a user email:

recently we have binout files (LS-Dyna R12.10), which do not contain a nodout array anymore, if you read them with lasso-python 2.0.0. under Windows. With lasso-python1.5.2.post1 this also occurred. Under Linux it works with the 1.5.2.post1 however as it should, i.e. the nodout array is read correctly. With Meta / LS-PrePost the binout can also be read correctly.

**🔢 To Reproduce**

1. Read a binout file with `nodout` on windows
2. Check for nodout

**💘 Expected behavior**
Nodout should be readable.

**🖥️ Setup**
 - lasso-python version: 1.5.2post1
 - OS: Windows

**Comment by ballaln** [comment]
I am currently not using R12.10. Do you have a test binout file to monitor the issue?

**Comment by codie3611** [comment]
Would close as no further message was given for thee time being
