### ISSUE TITLE
sklearn still used as a dependency instead of scikit-learn -> install will gradually fail more and more

### ISSUE THREAD

**Issue by dani2112** [open-lasso-python/lasso-python#36]
**🐛 Describe the bug**
The correct package name for scikit-learn is scikit-learn not sklearn. The sklearn package did work but is now deprecated and implements the brownout strategy, so will gradually increase failure on install. See also https://pypi.org/project/sklearn/.
Also see the old issue in the legacy repo from when their were still no issues with failures: https://github.com/open-lasso-python/lasso-python-legacy/issues/15

**🔢 To Reproduce**
Steps to reproduce the behavior: Install during times mentioned in brownout strategy description.

**💘 Expected behavior**
Install the correct package and do not rely on mechanisms that should prevent users from installing malicious code.

**🖥️ Setup**
 - lasso-python version: 2.0.0
 - OS: Ubuntu

**Comment by codie3611** [comment]
Thanks for reporting. This will be a quick fix :+1:
