### ISSUE TITLE
sklearn deprecated

### ISSUE THREAD

**Issue by ThomasBoulestin** [open-lasso-python/lasso-python#41]
Hello !

On installation, pip throw an error because of this :    

Here is how to fix this error in the main use cases:
    - use 'pip install scikit-learn' rather than 'pip install sklearn'
    - replace 'sklearn' by 'scikit-learn' in your pip requirements files
      (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
    - if the 'sklearn' package is used by one of your dependencies,
      it would be great if you take some time to track which package uses
      'sklearn' instead of 'scikit-learn' and report it to their issue tracker
    - as a last resort, set the environment variable
      SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

It might be good to update requirements.txt file

Cheers,

**Comment by ThomasBoulestin** [comment]
Seems to works when using :

python -m pip install lasso-python

instead of :

pip install -r requirements.txt

**Comment by codie3611** [comment]
Yes indeed I updated the pip package to now use the right package :+1:
