### ISSUE TITLE
Get the strain energy data for dyna

### ISSUE THREAD

**Issue by Mengmeng0315** [open-lasso-python/lasso-python#42]
Hello, 
Recently I want to get the strain energy of the specific solid elements  using lasso python. 
but I don’t find out the relevant key in d3plot library. 
Do you have any idea how to get these information? 
thank you so much

**Comment by WillemJR** [comment]
Yes, it’s a history variable. #5? Check which one using ls-prepost. For solids you have to activate using EXTEND_DATABASE (unsure about exact keyword name)
