### ISSUE TITLE
Node_displacement not correct

### ISSUE THREAD

**Issue by qilinli** [open-lasso-python/lasso-python#43]
Many thanks for the work. Upon usage, I found the output of the array "node_displacement" does not make sense. Any clue on that?

**Comment by manuel1618** [comment]
A little more info would be great. What was your input, what was your expected output and how did it compare to the actual output?

**Comment by codie3611** [comment]
The name was taken originally from the manual but is indeed wrong. It is the node coordinates over time.

**Comment by qilinli** [comment]
Ah...node coordinates make perfect sense. Cheers!
