### ISSUE TITLE
D3plot state_array_filter does not include all valid options

### ISSUE THREAD

**Issue by turnerjennings** [open-lasso-python/lasso-python#45]
In lasso-dyna D3plot, when trying to apply a state_array_filter to a D3plot file being loaded, the option "element_solid_ids" is not recognized.  The "element_solid_ids" is a valid ArrayType and is loaded when no state_array_filter is applied, but a ValueError is raised when trying to apply that ArrayType as a filter.

**Loading without a state array filter**
```
d3plot = D3plot(input_path, buffered_reading=True)
element_solid_ids = d3plot.arrays["element_solid_ids"]

Return: array of solid ids
```

**loading with a state array filter**
```
d3plot = D3plot(input_path, buffered_reading=True, state_array_filter=["element_solid_ids"])

Return: ValueError: Array 'element_solid_ids' is not a state array.
```

**Comment by codie3611** [comment]
The reason is that solid ids are part of the geometry and are not as stated a state array. You can only filter for state arrays and not geometry arrays, which is usually not an issue as geometry is tiny compared to state arrays.
