### ISSUE TITLE
UTF-8 encoding on part names to prevent crash

### ISSUE THREAD

**Issue by Vortex-CAE** [open-lasso-python/lasso-python#47]
ASCII encoding was causing some post-processors to crash when displaying part name, UTF-8 resolves this

![image](https://github.com/open-lasso-python/lasso-python/assets/144378169/26cdc4dd-8dc2-4f4d-87be-0baaa88553b1)

Many thanks

**Comment by codie3611** [comment]
You want to open a PR for this? We ought to encode generally in utf-8.

**Comment by Vortex-CAE** [comment]
Sure - Done
