### ISSUE TITLE
Check docs for wrong information

### ISSUE THREAD

**Issue by codie3611** [open-lasso-python/lasso-python#7]
Check the docs for the following wrong information:

- Remove indicator for some features which were previously flagged as "pro"
- Remove email and website references to LASSO as the project belongs to the community now

**Comment by ballaln** [comment]
@codie3611 Should we retain Lasso logo or can it be deleted?

**Comment by codie3611** [comment]
Hmmm what do you think? We don't have another logo so I would keep it. Also as a thanks to the company for open-sourcing the code.

**Comment by ballaln** [comment]
> Hmmm what do you think? We don't have another logo so I would keep it. Also as a thanks to the company for open-sourcing the code.

@codie3611 sounds good to me. It is fair enough.
